//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Stanton.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        internal static string D_Filter {
            get {
                return ResourceManager.GetString("D_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1,Show filtered results
        ///F2,Refine
        ///F5,Refresh
        ///F10,Keep on top.
        /// </summary>
        internal static string D_FuncKeys {
            get {
                return ResourceManager.GetString("D_FuncKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep on top.
        /// </summary>
        internal static string D_KOT {
            get {
                return ResourceManager.GetString("D_KOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl,Load direct
        ///Alt,Show other
        ///Shift,Open raw
        ///Alt+Ctrl,Download.
        /// </summary>
        internal static string D_ModifierKeys {
            get {
                return ResourceManager.GetString("D_ModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string D_N {
            get {
                return ResourceManager.GetString("D_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification image.
        /// </summary>
        internal static string D_NI {
            get {
                return ResourceManager.GetString("D_NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority engines.
        /// </summary>
        internal static string D_PE {
            get {
                return ResourceManager.GetString("D_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search engines.
        /// </summary>
        internal static string D_SE {
            get {
                return ResourceManager.GetString("D_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ding {
            get {
                return ResourceManager.GetStream("ding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream hint {
            get {
                return ResourceManager.GetStream("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/issues/new.
        /// </summary>
        internal static string U_Issue {
            get {
                return ResourceManager.GetString("U_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/blob/master/README.md.
        /// </summary>
        internal static string U_Readme {
            get {
                return ResourceManager.GetString("U_Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage.
        /// </summary>
        internal static string U_Repo {
            get {
                return ResourceManager.GetString("U_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/wiki.
        /// </summary>
        internal static string U_Wiki {
            get {
                return ResourceManager.GetString("U_Wiki", resourceCulture);
            }
        }
    }
}
