//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Stanton.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream hint {
            get {
                return ResourceManager.GetStream("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engines.
        /// </summary>
        internal static string K_Engines {
            get {
                return ResourceManager.GetString("K_Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        internal static string K_Filter {
            get {
                return ResourceManager.GetString("K_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification.
        /// </summary>
        internal static string K_Notification {
            get {
                return ResourceManager.GetString("K_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification-image.
        /// </summary>
        internal static string K_NotificationImage {
            get {
                return ResourceManager.GetString("K_NotificationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output-only.
        /// </summary>
        internal static string K_OutputOnly {
            get {
                return ResourceManager.GetString("K_OutputOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priority-engines.
        /// </summary>
        internal static string K_PriorityEngines {
            get {
                return ResourceManager.GetString("K_PriorityEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1,Show filtered results
        ///F2,Refine
        ///F5,Refresh.
        /// </summary>
        internal static string KeyFunctionDesc {
            get {
                return ResourceManager.GetString("KeyFunctionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl,Load direct
        ///Alt,Show other
        ///Shift,Open raw
        ///Alt+Ctrl,Download.
        /// </summary>
        internal static string KeyModifiersDesc {
            get {
                return ResourceManager.GetString("KeyModifiersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        internal static string S_Filter {
            get {
                return ResourceManager.GetString("S_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE.
        /// </summary>
        internal static string S_PE {
            get {
                return ResourceManager.GetString("S_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string S_SE {
            get {
                return ResourceManager.GetString("S_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/issues/new.
        /// </summary>
        internal static string UrlIssue {
            get {
                return ResourceManager.GetString("UrlIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/blob/master/README.md.
        /// </summary>
        internal static string UrlReadme {
            get {
                return ResourceManager.GetString("UrlReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage.
        /// </summary>
        internal static string UrlRepo {
            get {
                return ResourceManager.GetString("UrlRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/wiki.
        /// </summary>
        internal static string UrlWiki {
            get {
                return ResourceManager.GetString("UrlWiki", resourceCulture);
            }
        }
    }
}
