//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Lib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Stanton.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartImage.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\SmartImage.
        /// </summary>
        internal static string Reg_Shell {
            get {
                return ResourceManager.GetString("Reg_Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Classes\*\shell\SmartImage\command.
        /// </summary>
        internal static string Reg_Shell_Cmd {
            get {
                return ResourceManager.GetString("Reg_Shell_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage.
        /// </summary>
        internal static string Repo_Url {
            get {
                return ResourceManager.GetString("Repo_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-search.
        /// </summary>
        internal static string S_AutoSearch {
            get {
                return ResourceManager.GetString("S_AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard detection.
        /// </summary>
        internal static string S_Clipboard {
            get {
                return ResourceManager.GetString("S_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        internal static string S_ContextMenu {
            get {
                return ResourceManager.GetString("S_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh Password.
        /// </summary>
        internal static string S_EhPassword {
            get {
                return ResourceManager.GetString("S_EhPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh Username.
        /// </summary>
        internal static string S_EhUsername {
            get {
                return ResourceManager.GetString("S_EhUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On top.
        /// </summary>
        internal static string S_OnTop {
            get {
                return ResourceManager.GetString("S_OnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open raw.
        /// </summary>
        internal static string S_OpenRaw {
            get {
                return ResourceManager.GetString("S_OpenRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority engines.
        /// </summary>
        internal static string S_PriorityEngines {
            get {
                return ResourceManager.GetString("S_PriorityEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SauceNao Key.
        /// </summary>
        internal static string S_SauceNaoKey {
            get {
                return ResourceManager.GetString("S_SauceNaoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search engines.
        /// </summary>
        internal static string S_SearchEngines {
            get {
                return ResourceManager.GetString("S_SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send-to menu.
        /// </summary>
        internal static string S_SendTo {
            get {
                return ResourceManager.GetString("S_SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        internal static string S_Silent {
            get {
                return ResourceManager.GetString("S_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/wiki.
        /// </summary>
        internal static string Wiki_Url {
            get {
                return ResourceManager.GetString("Wiki_Url", resourceCulture);
            }
        }
    }
}
