//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Lib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href.
        /// </summary>
        internal static string Atr_href {
            get {
                return ResourceManager.GetString("Atr_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Atr_id {
            get {
                return ResourceManager.GetString("Atr_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-search.
        /// </summary>
        internal static string S_AutoSearch {
            get {
                return ResourceManager.GetString("S_AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On top.
        /// </summary>
        internal static string S_OnTop {
            get {
                return ResourceManager.GetString("S_OnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority engines.
        /// </summary>
        internal static string S_PriorityEngines {
            get {
                return ResourceManager.GetString("S_PriorityEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search engines.
        /// </summary>
        internal static string S_SearchEngines {
            get {
                return ResourceManager.GetString("S_SearchEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Tag_a {
            get {
                return ResourceManager.GetString("Tag_a", resourceCulture);
            }
        }
    }
}
