//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartImage.cfg.
        /// </summary>
        internal static string F_Config {
            get {
                return ResourceManager.GetString("F_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engines.
        /// </summary>
        internal static string K_Engines {
            get {
                return ResourceManager.GetString("K_Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        internal static string K_Filter {
            get {
                return ResourceManager.GetString("K_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification.
        /// </summary>
        internal static string K_Notification {
            get {
                return ResourceManager.GetString("K_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification-image.
        /// </summary>
        internal static string K_NotificationImage {
            get {
                return ResourceManager.GetString("K_NotificationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output-only.
        /// </summary>
        internal static string K_OutputOnly {
            get {
                return ResourceManager.GetString("K_OutputOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priority-engines.
        /// </summary>
        internal static string K_PriorityEngines {
            get {
                return ResourceManager.GetString("K_PriorityEngines", resourceCulture);
            }
        }
    }
}
