//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Serialization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Serialization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Lib.Serialization", typeof(Serialization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href.
        /// </summary>
        internal static string Atr_href {
            get {
                return ResourceManager.GetString("Atr_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Atr_id {
            get {
                return ResourceManager.GetString("Atr_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(@class, &apos;info-box&apos;)].
        /// </summary>
        internal static string S_Ascii2D_Images {
            get {
                return ResourceManager.GetString("S_Ascii2D_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[contains(@class, &apos;item-box&apos;)].
        /// </summary>
        internal static string S_Ascii2D_Images2 {
            get {
                return ResourceManager.GetString("S_Ascii2D_Images2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table/tbody/tr.
        /// </summary>
        internal static string S_EHentai {
            get {
                return ResourceManager.GetString("S_EHentai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pages &gt; div.nomatch.
        /// </summary>
        internal static string S_Iqdb_NoMatches {
            get {
                return ResourceManager.GetString("S_Iqdb_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;pages&apos;].
        /// </summary>
        internal static string S_Iqdb_Pages {
            get {
                return ResourceManager.GetString("S_Iqdb_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table &gt; tbody &gt; tr:nth-child(n).
        /// </summary>
        internal static string S_Iqdb_Table {
            get {
                return ResourceManager.GetString("S_Iqdb_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .resultcontentcolumn.
        /// </summary>
        internal static string S_SauceNao_ResultContentColumn {
            get {
                return ResourceManager.GetString("S_SauceNao_ResultContentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class, &apos;Tags-Item&apos;) and ../../../../div[contains(@class,&apos;CbirTags&apos;)]]/*.
        /// </summary>
        internal static string S_Yandex_Analysis {
            get {
                return ResourceManager.GetString("S_Yandex_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .CbirTags &gt; .Tags &gt; .Tags-Wrapper &gt; .Tags-Item.
        /// </summary>
        internal static string S_Yandex_Analysis2 {
            get {
                return ResourceManager.GetString("S_Yandex_Analysis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[contains(@class,&apos;CbirSites-Item&apos;)].
        /// </summary>
        internal static string S_Yandex_ExtInfo {
            get {
                return ResourceManager.GetString("S_Yandex_ExtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(@class, &apos;Tags-Item&apos;)].
        /// </summary>
        internal static string S_Yandex_Images {
            get {
                return ResourceManager.GetString("S_Yandex_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //li[@class=&apos;other-sites__item&apos;].
        /// </summary>
        internal static string S_Yandex_OtherImages {
            get {
                return ResourceManager.GetString("S_Yandex_OtherImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .CbirSimilar-Thumb.
        /// </summary>
        internal static string S_Yandex_SimilarImages {
            get {
                return ResourceManager.GetString("S_Yandex_SimilarImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Tag_a {
            get {
                return ResourceManager.GetString("Tag_a", resourceCulture);
            }
        }
    }
}
