<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SmartImage.Lib</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;Test;UnitTest</Configurations>
    <Nullable>disable</Nullable>
    <DefineConstants>JETBRAINS_ANNOTATIONS;TRACE</DefineConstants>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>True</PublishTrimmed>
    <!-- <PublishSingleFile>true</PublishSingleFile> -->

    <PublishSingleFile Condition="'$(Configuration)' == 'Release|AnyCPU'">true</PublishSingleFile>

    <NoWarn>$(NoWarn);AD0001;IDE0290;CS0168;IDE0290;CA2255;CA1873;CA1822;IDE0300;IDE0290;IDE0079;1701;1702;NU1608;IDE0300;IDE0059;SI_EXP_001</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <SatelliteResourceLanguages>en-US;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;JETBRAINS_ANNOTATIONS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Test|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;JETBRAINS_ANNOTATIONS;TEST</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='UnitTest|AnyCPU'">
    <DefineConstants>DEBUG;TRACE;JETBRAINS_ANNOTATIONS;TEST</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SmartImage.Lib.csproj.Backup.tmp" />
    <None Remove="SmartImage.Lib.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.4.0" />
    <PackageReference Include="AngleSharp.Css" Version="1.0.0-alpha-99" />
    <PackageReference Include="AngleSharp.XPath" Version="2.0.6" />
    <PackageReference Include="CliWrap" Version="3.10.0" />
    <PackageReference Include="CoenM.ImageSharp.ImageHash" Version="1.3.6" />
    <PackageReference Include="CommunityToolkit.Common" Version="8.4.0" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="HttpMultipartParser" Version="10.0.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Validation" Version="17.13.22" />
    <!-- <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" /> -->
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.3" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
    <!-- <PackageReference Include="System.Net.Primitives" Version="4.3.1" /> -->
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.3" />
    <!-- <PackageReference Include="System.Text.Json" Version="10.0.1" /> -->
    <PackageReference Include="Verify.Flurl" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FlareSolverrSharp">
      <HintPath>..\..\..\VSProjects\FlareSolverrSharp\src\FlareSolverrSharp\bin\Release\net10.0\FlareSolverrSharp.dll</HintPath>
    </Reference>
    <Reference Include="Kantan">
      <HintPath>..\..\..\VSProjects\Kantan\Kantan\bin\Release\net10.0\Kantan.dll</HintPath>
    </Reference>
    <Reference Include="Kantan.Net">
      <HintPath>..\..\..\VSProjects\Kantan\Kantan.Net\bin\Release\net10.0\Kantan.Net.dll</HintPath>
    </Reference>
    <Reference Include="Novus">
      <HintPath>..\..\..\VSProjects\Novus\Novus\bin\Release\net10.0\Novus.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="FlareSolverrSharp" />
    <TrimmerRootAssembly Include="System.Net" />
    <TrimmerRootAssembly Include="System.IO.FileSystem" />
    <TrimmerRootAssembly Include="Novus" />
    <TrimmerRootAssembly Include="Kantan" />
    <TrimmerRootAssembly Include="System.Text.Json" />

    <TrimmerRootAssembly Include="System.Runtime.Caching" />
    <TrimmerRootAssembly Include="System.Configuration.ConfigurationManager" />

  </ItemGroup>
  <ItemGroup>
    <Compile Update="Serialization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Serialization.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Serialization.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Serialization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Import Project="..\..\..\VSProjects\SmartImage.Shared\SmartImage.Shared.projitems" Label="Shared" />

</Project>