//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartImage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartImage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --auto.
        /// </summary>
        internal static string Arg_AutoSearch {
            get {
                return ResourceManager.GetString("Arg_AutoSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --i.
        /// </summary>
        internal static string Arg_Input {
            get {
                return ResourceManager.GetString("Arg_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --noui.
        /// </summary>
        internal static string Arg_NoUI {
            get {
                return ResourceManager.GetString("Arg_NoUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --queue.
        /// </summary>
        internal static string Arg_Queue {
            get {
                return ResourceManager.GetString("Arg_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Stanton.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        internal static string C_Input {
            get {
                return ResourceManager.GetString("C_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ding {
            get {
                return ResourceManager.GetStream("ding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream hint {
            get {
                return ResourceManager.GetStream("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Inf_Cancel {
            get {
                return ResourceManager.GetString("Inf_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard data.
        /// </summary>
        internal static string Inf_Clipboard {
            get {
                return ResourceManager.GetString("Inf_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Inf_Complete {
            get {
                return ResourceManager.GetString("Inf_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        internal static string Int_ContextMenu {
            get {
                return ResourceManager.GetString("Int_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartImage.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage.
        /// </summary>
        internal static string Repo_Url {
            get {
                return ResourceManager.GetString("Repo_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Decimation/SmartImage/wiki.
        /// </summary>
        internal static string Wiki_Url {
            get {
                return ResourceManager.GetString("Wiki_Url", resourceCulture);
            }
        }
    }
}
